IIA-8-Login Api calls and routing
iOSinternshipen/EnMovie pull request #10
Opened 2021-10-31 16:56 UTC by colac-carla-30126

2021-11-01 10:14 UTC, iulia-anisoi-endava submitted a review, later dismissed

2021-11-01 11:20 UTC, colac-carla-30126 commented
<img width="370" alt="Screenshot 2021-11-01 at 13 15 35" src="https://user-images.githubusercontent.com/61448536/139663860-32fa2779-9e52-4294-96cd-a246922d86b5.png">

2021-11-01 12:59 UTC, SaniutaRobert submitted a review, later dismissed

2021-11-01 16:23 UTC, evakiraly submitted a review, later dismissed

2021-11-01 19:25 UTC, iulia-anisoi-endava submitted a review, later dismissed

2021-11-03 08:17 UTC, iulia-anisoi-endava commented on EnMovie/Modules/SignIn/SignInViewController.swift
>      @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
@IBOutlets should be marked private

2021-11-03 08:22 UTC, iulia-anisoi-endava approved these changes

2021-11-03 08:22 UTC, iulia-anisoi-endava commented on EnMovie/Modules/SignIn/SignInViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
@IBOutlets should be marked private

2021-11-03 10:31 UTC, vrincean-alex requested changes

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +    var expires_at: String?
Swift uses camelCase practice, I got that you want to direclty decrypt but in your case you should use CodingKeys instead. (check UpcomingMovies)

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> + struct RequestTokenEntity: Codable {
Structs are value type, to prevent bugs you should have let properties instead of var.

(in case you still don't understand the reason, please contact me)

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +fileprivate struct CreateSessionRequestEntity: Codable {
let -> var

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +    case apiKey = "9205ca5a40a3611616d67595d4523403"
you could use static let apiKey = "yourApiKey"

this change will help you lose that ugly ".rawValue"

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +            print("request token: \(String(describing: requestToken))")
This does not belong in the final release, nor the master(main) branch

Prints should be used only to point out errors.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +                print("session token: \(String(describing: sessionToken))")
same as above

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +                // save sessios token ul in userDefaults
Comments are great, but please correct the typos.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +        if let encoded = try? encoder.encode(sessionToken) {
If you only use the JSONEncoder() once, you don't need to create a let for it, because it will only make your code bigger. We want our code to be short and concise.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +            let userDefaults = UserDefaults.standard
same as above.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +        let session = URLSession.shared
same as before.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInInteractor.swift
> +        let session = URLSession.shared
same as before.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInRouter.swift
> +//
Please remove the commented code.

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInViewController.swift
> +    let yourAttributes: [NSAttributedString.Key: Any] = [ .underlineStyle: NSUnderlineStyle.single.rawValue ]
Can you rename the property to a better name that will give a hint about the property itself ?

"yourAttributes" does not hint anything to me

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInViewController.swift
> +              !username.isEmpty,
Be aware that .isEmpty does not check for spaces

ex: "        ". isEmpty -> false

2021-11-03 10:31 UTC, vrincean-alex commented on EnMovie/Modules/SignIn/SignInViewController.swift
> +    func startLoading() {
Can you merge the startLoading() and stopLoading() into one single method ?

2021-11-04 13:41 UTC, vrincean-alex approved these changes

2021-11-04 14:21 UTC, iulia-anisoi-endava submitted a review, later dismissed

2021-11-04 14:39 UTC, iulia-anisoi-endava approved these changes

2021-11-04 14:40 UTC, GeorgeCuciureanu approved these changes

2021-11-04 14:41 UTC, merged