Feature/movie details screen
iOSinternshipen/EnMovie pull request #17
Opened 2021-11-04 14:51 UTC by evakiraly

<img width="685" alt="Screenshot 2021-11-08 at 09 29 51" src="https://user-images.githubusercontent.com/93143080/140701127-6d8e66e7-d4b1-4cae-864c-e888bf3daa46.png">
<img width="685" alt="Screenshot 2021-11-08 at 09 29 15" src="https://user-images.githubusercontent.com/93143080/140701085-652e155d-e5a5-4cad-a22e-3b0d2a74e61c.png">

2021-11-04 15:16 UTC, iOSinternshipen requested changes

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/CustomDetailsView.swift
> +        detailsStackView.addArrangedSubview(detailLabel(movieYear ?? "-"))
remove the moviewYear ?? - and have a separate lazy var label for everything and set the text separately

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/CustomDetailsView.swift
> +        self.addSubview(detailsStackView)
self is no needed (respect the guidelines)

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/CustomDetailsView.swift
> +        detailsStackView.translatesAutoresizingMaskIntoConstraints = false
you can set this in lazy var

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/CustomRatingView.swift
> +import Foundation
similar as in another file

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/CustomRatingView.swift
> +        NSLayoutConstraint.activate(constraints)
all the comments from the previous view applies here

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsPresenter.swift
> +        print(error.localizedDescription)
should we show and error alert?

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsRouter.swift
> +}
you can keep it on one line

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsRouter.swift
> +}
similar

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsRouter.swift
> +}
one line

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +    func didGetResult(result: MovieDetailsDTO)
maybe have an alert for error case?

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +    private var ratingView: CustomRatingView = {
lazy var :D

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +    private var basicMovieInfosView = {(movieYear: String?, runtime: String?, categories: String?) -> CustomDetailsView in
lazy var and have a public method for setting year, runtime, categories

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +    @IBOutlet var indicatorView: UIActivityIndicatorView!
private?

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +    private var movie: MovieDetailsDTO?
move it with other private vars

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +
new line?

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +
new line not needed

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +        containerView.addSubview(imageContainerView)
do we need addsubview? is not already included in storyboard?

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/DetailsViewController.swift
> +        containerView.translatesAutoresizingMaskIntoConstraints = false
you can add constraints in storyboard? if not you can select translateAutoresizingMask = false from there

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/Entity/Movie.swift
> +import UIKit
do you need UIKit? it's a model file

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Details/MovieDetailsProvider.swift
> +            if let error = error {
use guard, example: guard let data = data and try decoded, an with else return the completion Error (you can change it to be optional in escaping)

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Home/Presenter/HomePresenter.swift
> +
new line not needed

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Home/View/Reusable Views/MoviesTableViewCell.swift
> +    private var selectedMovieId: Int?
don't need this?

2021-11-04 15:16 UTC, iOSinternshipen commented on EnMovie/Modules/Home/View/Reusable Views/MoviesTableViewCell.swift
> +        self.movieCellDelegate?.cellWasPressed(movieId: selectedMovieId ?? 0)
you can send directly upcomingMoviesArray[indexPath.row].id without and don't need to have a private var for it

2021-11-08 07:01 UTC, barna-fulop approved these changes

2021-11-08 07:42 UTC, GeorgeCuciureanu approved these changes

2021-11-08 07:45 UTC, iulia-anisoi-endava approved these changes

2021-11-08 07:50 UTC, iOSinternshipen approved these changes

2021-11-08 08:01 UTC, merged