Profile Screen attempt
iOSinternshipen/EnMovie pull request #8
Opened 2021-10-29 06:50 UTC by colac-carla-30126

Profile Screen Design

2021-11-01 11:21 UTC, colac-carla-30126 commented
<img width="379" alt="Screenshot 2021-10-29 at 09 26 23" src="https://user-images.githubusercontent.com/61448536/139663911-2cc75594-d214-48cf-bcfd-e988624a5cee.png">

2021-11-01 11:26 UTC, iulia-anisoi-endava approved these changes

2021-11-01 13:00 UTC, SaniutaRobert submitted a review, later dismissed

2021-11-01 16:19 UTC, evakiraly submitted a review, later dismissed

2021-11-01 18:04 UTC, iulia-anisoi-endava approved these changes

2021-11-03 10:39 UTC, vrincean-alex commented on EnMovie/Modules/Profile/ProfileCustomTableViewCell.swift
> +    @IBOutlet weak var settingsAppImage: UIImageView!
Please use private outlets, it will keep you away from touching them by mistake

2021-11-03 10:39 UTC, vrincean-alex commented on EnMovie/Modules/Profile/ProfileViewController.swift
> +struct Settings {
User let instead of var

2021-11-03 10:40 UTC, vrincean-alex commented on EnMovie/Modules/Profile/ProfileViewController.swift
> +    @IBOutlet weak var profileTableView: UITableView!
same as above

2021-11-03 10:41 UTC, vrincean-alex commented on EnMovie/Modules/Profile/ProfileViewController.swift
> +    var settings: [Settings] = [ Settings(image: UIImage.init(systemName: "person.fill")!, text: "Account details"),
The guideline for arrays is the following:

var array: Array = [
             "1",
             "2",
             "3"
]

Also, you don't ready need the ".init"

2021-11-03 10:43 UTC, vrincean-alex requested changes
Please resolve the requested changes.

2021-11-04 13:43 UTC, vrincean-alex approved these changes

2021-11-04 14:21 UTC, iulia-anisoi-endava submitted a review, later dismissed

2021-11-04 14:31 UTC, GeorgeCuciureanu approved these changes

2021-11-04 14:52 UTC, GeorgeCuciureanu approved these changes

2021-11-04 15:00 UTC, evakiraly approved these changes

2021-11-04 15:00 UTC, merged